## Final Project Submission

Please fill out:
* Student name: Griffin Kinyua
* Student pace: full time
* Scheduled project review date/time: 21/08/2026
* Instructor name: Samuel G. Mwangi
* Blog post URL:

Loading im.db dataset

In [ ]:
import zipfile

# Extracting im.db from the zip file inside zippedData
with zipfile.ZipFile('zippedData/im.db.zip', 'r') as zip_ref:
    zip_ref.extractall('zippedData/')

Connecting to the SQLite Database

In [3]:
import sqlite3
import pandas as pd

# Connecting to the unzipped SQLite database
conn = sqlite3.connect('zippedData/im.db')

Inspecting the dataset

Checking the tables in the dataset

In [5]:
# Listing all tables in the database
query = "SELECT name FROM sqlite_master WHERE type='table';"
tables = pd.read_sql_query(query, conn)
display(tables)

            name
0   movie_basics
1      directors
2      known_for
3     movie_akas
4  movie_ratings
5        persons
6     principals
7        writers

In [ ]:
# Loading the FULL table into Pandas 
movies_df = pd.read_sql('SELECT * FROM movie_basics;', conn)

# Checking missing values across ALL rows
print(movies_df.isnull().sum())

# Inspecting a sample of 10 rows in Pandas instead of SQL
display(movies_df.head(10))

conn.close()

movie_id               0
primary_title          0
original_title        21
start_year             0
runtime_minutes    31739
genres              5408
dtype: int64

,movie_id,primary_title,original_title,start_year,runtime_minutes,genres
0,tt0063540,Sunghursh,Sunghursh,2013,175.0,"Action,Crime,Drama"
1,tt0066787,One Day Before the Rainy Season,Ashad Ka Ek Din,2019,114.0,"Biography,Drama"
2,tt0069049,The Other Side of the Wind,The Other Side of the Wind,2018,122.0,Drama
3,tt0069204,Sabse Bada Sukh,Sabse Bada Sukh,2018,NaN,"Comedy,Drama"
4,tt0100275,The Wandering Soap Opera,La Telenovela Errante,2017,80.0,"Comedy,Drama,Fantasy"
5,tt0111414,A Thin Life,A Thin Life,2018,75.0,Comedy
6,tt0112502,Bigfoot,Bigfoot,2017,NaN,"Horror,Thriller"
7,tt0137204,Joe Finds Grace,Joe Finds Grace,2017,83.0,"Adventure,Animation,Comedy"
8,tt0139613,O Silêncio,O Silêncio,2012,NaN,"Documentary,History"
9,tt0144449,Nema aviona za Zagreb,Nema aviona za Zagreb,2012,82.0,Biography